### ISSUE TITLE
User can see open issues

### ISSUE THREAD

**Issue by ghost** [xternprojects/cultural-trail-android#7]
It needs to be easy to switch between list and map view
- [ ] #8 - List of issues
- [ ] #9 - Map of issues
- [ ] #10 - Open issue details
- [ ] #11 - Issue details includes pictures, GPS, description, etc.
